name: CI
on: push

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      clients: ${{ steps.environments.outputs.clients }}
    steps:
      - name: Get defined clients from codebase
        shell: bash
        run: |
          echo "environments:\n  main:\n  main-2:\n---\ntest nothing good here" | awk '/^---$/ { exit } { print }' | yq '.environments | keys' -o=j -I=0 | awk '{print "clients="$1}'
      - name: Get defined clients from codebase
        id: environments
        shell: bash
        # Output example: clients=["main","main-mpfx",...]
        run: |
          echo "environments:\n  main:\n  main-2:\n---\ntest nothing good here" | awk '/^---$/ { exit } { print }' | yq '.environments | keys' -o=j -I=0 | awk '{print "clients="$1}' >> $GITHUB_OUTPUT

  deploy:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        client: ${{ fromJson(needs.prepare.outputs.clients) }}
    steps:
    - name: Get defined clients from codebase
      shell: bash
      run: echo "${{ matrix.client }}"
