name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: chrisdickinson/setup-yq@latest
    - name: Show folks how to run YQ:
      run: |
        awk '/---/ {exit} 1' dev.yaml | yq '.environments | keys[]'
