name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set SELECTORS for helmfile
      shell: bash
      run: echo "BACKEND_IMAGE_TAG=v1.0.1" | sed 's/\([A-Z_]*\)_IMAGE_TAG=[^ ]*/-l name=\1/g' | awk '{print "HELMFILE_SELECTORS=\"" tolower($0) "\""}' >> $GITHUB_ENV
    - name: Deploy client
      uses: helmfile/helmfile-action@main
      with:
        helmfile-auto-init: "true"
        helmfile-args: apply -f test.yaml -e main-test ${{ toJson(env.HELMFILE_SELECTORS) }}
